### ISSUE TITLE
How to install existing @koopjs auth/provider plugins?

### ISSUE THREAD

**Issue by mttjhn** [koopjs/koop-cli#28]
I'm wanting to test out the koop-auth-direct-file auth plugin, and I tried to install by using the command: `koop add auth @koopjs/auth-direct-file`

Although the above command appeared to succeed, I am now getting an error when trying to run `koop serve` on my project: 
`Error: Cannot find module '@koopjs/auth-direct-file'`  

I'm expecting I missed something for getting this set up. Can you provide documentation for how to install existing/published plugins?

**Comment by haoliangyu** [comment]
@mttjhn Thank you for reporting this.

I have tested in on my local machine. Your steps are correct since the plugin has been registered in the `src/plugins.js` file. There seems to be a bug in installation code that messes up the plugin name.

If you check the `package.json`, there should be an invalid dependency:

``` json
"dependencies": {
    "undefined": "^0.1.0"
  }
```

We will work on a patch very soon!

**Comment by haoliangyu** [comment]
Please install the latest CLI version (0.3.3) and it should correctly install the plugin now.

Note that the `add` command is not yet able to handle the custom plugin initialization like the `@koopjs/auth-direct-file` does. You will need to manually modify the `src/plugins.js` like:

``` javascript
// from (the original line will not work)
const authDirectFile = require('@koopjs/auth-direct-file');

// to (the correct way)
const authDirectFile = require('@koopjs/auth-direct-file')('secret', `${__dirname}/user-store.json`);
```

I am closing this issue as the bug is resolved. If you still have other problems, we can continue to discuss here or at a new issue.

**Comment by mttjhn** [comment]
Thanks! It appears to be working now.
